version: "2"

services:
  # Nginx container
  dweb:
    build: ./web
    container_name: dweb
    volumes:
      - "${PATH_TO_LOCAL_PROJECT}:${PATH_TO_PROJECT_INSIDE_CONTAINER}"
    ports:
      - "${NGINX_PORT}:80"
    working_dir: ${PATH_TO_PROJECT_INSIDE_CONTAINER}
    links:
      - dpma
      - dmysql
  dmysql:
    image: mysql/mysql-server:5.6
    container_name: dmysql
    volumes:
      - "${MYSQL_PATH_TO_STORE_DB_LOCAL}:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
    ports:
      - "3308:${MYSQL_PORT}"
  dpma:
    image: phpmyadmin/phpmyadmin
    container_name: dpma
    volumes:
      - /sessions
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      PMA_HOST: "dmysql"
    ports:
      - "${PMA_PORT}:80"
    links:
      - dmysql
