version: "2"

services:
  br_web:
    container_name: br_web
    build: ./nginx
    volumes:
      - "${PATH_TO_LOCAL_PROJECT}:${PATH_TO_PROJECT_INSIDE_CONTAINER}"
      - "./dashboard.conf:/etc/nginx/conf.d/nginx.conf:ro"
    ports:
      - "${NGINX_PORT}:80"
    working_dir: ${PATH_TO_PROJECT_INSIDE_CONTAINER}
    links:
      - br_php
  br_php:
    build: ./php
    container_name: br_php
    volumes:
      - "${PATH_TO_LOCAL_PROJECT}:${PATH_TO_PROJECT_INSIDE_CONTAINER}"
    working_dir: ${PATH_TO_PROJECT_INSIDE_CONTAINER}
