version: "2"

services:
  # Nginx container
  d_nginx:
    image: nginx:latest
    container_name: d_nginx
    volumes:
      - "${PATH_TO_LOCAL_PROJECT}:${PATH_TO_PROJECT_INSIDE_CONTAINER}"
      - "./dashboard.conf:/etc/nginx/conf.d/nginx.conf:ro"
    ports:
      - "${NGINX_PORT}:80"
    working_dir: ${PATH_TO_PROJECT_INSIDE_CONTAINER}
    links:
      - d_php
  # Php-fpm container
  d_php:
    image: d_php:1.0.0
    build: ./php
    container_name: d_php
    volumes:
      - "${PATH_TO_LOCAL_PROJECT}:${PATH_TO_PROJECT_INSIDE_CONTAINER}"
    working_dir: ${PATH_TO_PROJECT_INSIDE_CONTAINER}