version: "3"

services:
  web:
    image: nginx
    volumes:
      - "${PATH_TO_LOCAL_PROJECT}:${PATH_TO_PROJECT_INSIDE_CONTAINER}"
      - "./dashboard.conf:/etc/nginx/conf.d/dashboard.conf"
    ports:
      - "${NGINX_PORT}:80"
    working_dir: ${PATH_TO_PROJECT_INSIDE_CONTAINER}
    links:
      - php
      - mysql
      - phpmyadmin
  mysql:
    image: mysql:latest
    container_name: db
    volumes:
      - "${MYSQL_PATH_TO_STORE_DB_LOCAL}:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
    ports:
      - "3308:${MYSQL_PORT}"
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:latest"
    restart: always
    volumes:
      - /sessions
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      PMA_HOST: "mysql"
    ports:
      - "${PMA_PORT}:80"
    links:
      - mysql
  php:
    build: ./php
    volumes:
      - "${PATH_TO_LOCAL_PROJECT}:${PATH_TO_PROJECT_INSIDE_CONTAINER}"
    working_dir: ${PATH_TO_PROJECT_INSIDE_CONTAINER}
    links:
      - mysql
